# Generated by Django 4.0.4 on 2022-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasttag', '0002_users_fastid_users_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='accbal',
            field=models.IntegerField(default=0),
        ),
    ]
