# Generated by Django 4.0.4 on 2022-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasttag', '0003_users_accbal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='fastid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
